# Site settings_dirc
title: MainQuest - Soluções Audiovisuais
description: > #
  MainQuest - Soluções Audiovisuais
  Filmamos, fotografamos, fazemos vinhetas, animações em 2D ou 3D...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mainquest.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css/_sass
  style: :expanded
