# Site settings_dirc
title: MainQuest - Soluções Audiovisuais
description: > #
  Soluções Audiovisuais. Animações, vinhetas, webvídeos, institucionais.
  Tem uma idéia ou precisa de alguma? Vamos conversar, entre em contato.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.mainquest.com.br" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css/_sass
  style: :expanded
